FROM: php:7.2-apache

COPY . /var/www/html/

ENV REDIS_OPTIONS_SCHEMA "tcp"
ENV REDIS_OPTIONS_HOST "localhost"
ENV REDIS_OPTIONS_PORT "6379"
ENV REDIS_OPTIONS_PASSWORD "changeme"

ENV RETWIS_TITLE "Moin"

